### ISSUE TITLE
Add shopping cart page, and a link to it in the navbar

### ISSUE THREAD

**Issue by Kibuns** [Kibuns/Webshop-ChicnChoc#16]
Regards user story #2 
nothing needs to actually function just yet. Only an empty page that will eventually have a shopping cart. And a link to that page, ~preferably~ using a shopping cart IconButton in the navbar

see: 
- https://mui.com/components/icons/
- https://mui.com/components/material-icons/

**Comment by kokoaono** [comment]
@Kibuns can I have a go please?

**Comment by longwaytogofromnow** [comment]
@Kibuns can I work on this issue?
